wget -O M_musculu.fa.gz ftp://ftp.ncbi.nih.gov/genomes/M_musculus/protein/protein.fa.gz
wget -O Bos_taurus.fa.gz ftp://ftp.ncbi.nih.gov/genomes/Bos_taurus/protein/protein.fa.gz
wget -O Canis_familiaris.fa.gz ftp://ftp.ncbi.nih.gov/genomes/Canis_familiaris/protein/protein.fa.gz
wget -O D_rerio.fa.gz ftp://ftp.ncbi.nih.gov/genomes/D_rerio/protein/protein.fa.gz
wget -O Equus_caballus.fa.gz ftp://ftp.ncbi.nih.gov/genomes/Equus_caballus/protein/protein.fa.gz
wget -O Gallus_gallus.fa.gz ftp://ftp.ncbi.nih.gov/genomes/Gallus_gallus/protein/protein.fa.gz
wget -O H_sapiens.fa.gz ftp://ftp.ncbi.nih.gov/genomes/H_sapiens/protein/protein.fa.gz
wget -O Macaca_mulatta.fa.gz ftp://ftp.ncbi.nih.gov/genomes/Macaca_mulatta/protein/protein.fa.gz
wget -O R_norvegicus.fa.gz ftp://ftp.ncbi.nih.gov/genomes/R_norvegicus/protein/protein.fa.gz